import { Translations } from "@/types"

export const en : Translations = {
    presentation : "Discover Endless Possibilities with",
    fullPresentation : "Where creativity meets innovations : embark on a journey of limitless exploration with AI Zone",
    Continue_with_Email : "Continue with Email",
    Please_fill_in_all_the_fields : "Please fill in all the fields",
    Password : "Password",
    Username : "Username",
    Don_t_have_an_account : "Don't have an account ?",
    Have_an_account_already : "Have an account already? ",
    Sign_up : "Sign up",
    Sign_in : "Sign in",
    Saved_Videos : "Saved Videos",
    Create_Videos : "Create_Videos",
    No_Videos_Found : "No Videos Found",
    No_videos_found_for_this_search : "No videos found for this search",
    Succes : "Succes",
    Post_uploaded_successfully : "Post uploaded successfully",
    Upload_Video : "Upload Video",
    Video_Title : "Video Title",
    Give_Your_video_a_catch_title : "Give Your video a catch title...",
    Thumbnail_Image : "Thumbnail Image",
    Choose_a_file : "Choose a file",
    AI_Prompt : "AI Prompt",
    The_prompt_you_use_to_create_this_video : "The prompt you use to create this video",
    Submit_Publish : "Submit & Publish",
    Welcome_Back : "Welcome Back",
    Search_for_a_video_topic : "Search for a video topic",
    Latest_videos : "Latest videos",
    Be_the_first_one_to_upload_a_video : "Be the first one to upload a video",
    Post : "Post",
    Followes : "Followes",
    Search_Result : "Search Result",
    Home : "Home",
    Bookmark : "Bookmark",
    Create : "Create",
    Profile : "Profile",
    Error : "Error",
    Log_in_to_Aora : "Log in to AI Zone",
    Sign_up_to_Aora  : "Sign up to AI Zone",
    Language : "Language",
    french : "french",
    english : "english",

    // le component searchinput 
    
    Missing_Query : "Missing Query",
    Missing_Query_details : "Please input something to search results across database"
}

export const fr: Translations = {
    presentation : "Découvrez des possibilités infinies avec",
    fullPresentation : "Là où la créativité rencontre l'innovation : embarquez pour un voyage d'exploration sans limites avec AI Zone",
    Continue_with_Email : "Continuer avec l'Email",
    Please_fill_in_all_the_fields : "Veuillez remplir tous les champs",
    Password : "Mot de passe",
    Username : "Nom d'utilisateur",
    Don_t_have_an_account : "Vous n'avez pas de compte ?",
    Have_an_account_already : "Vous avez déjà un compte ?",
    Sign_up : "S'inscrire",
    Sign_in : "Se connecter",
    Saved_Videos : "Vidéos sauvegardées",
    Create_Videos : "Creer des videos",
    No_Videos_Found : "Aucune vidéo trouvée",
    No_videos_found_for_this_search : "Aucune vidéo trouvée pour cette recherche",
    Succes : "Succès",
    Post_uploaded_successfully : "Publication téléchargée avec succès",
    Upload_Video : "Télécharger une vidéo",
    Video_Title : "Titre de la vidéo",
    Give_Your_video_a_catch_title : "Donnez un titre accrocheur à votre vidéo...",
    Thumbnail_Image : "Image miniature",
    Choose_a_file : "Choisir un fichier",
    AI_Prompt : "Invite AI",
    The_prompt_you_use_to_create_this_video : "L'invite que vous utilisez pour créer cette vidéo",
    Submit_Publish : "Soumettre et publier",
    Welcome_Back : "Bon retour",
    Search_for_a_video_topic : "Rechercher un sujet de vidéo",
    Latest_videos : "Dernières vidéos",
    Be_the_first_one_to_upload_a_video : "Soyez le premier à télécharger une vidéo",
    Post : "Publication",
    Followes : "Abonnés",
    Search_Result : "Résultat de la recherche",
    Home : "Accueil",
    Bookmark : "Marque-page",
    Create : "Créer",
    Profile : "Profil",
    Error : "Erreur",
    Log_in_to_Aora : "Se connecter à AI Zone",
    Language : "Langue",
    Sign_up_to_Aora  : "S’inscrire à AI Zone",
    french : "Francais",
    english : "Anglais",

    // le component searchinput 
    
    Missing_Query : "Requête manquante",
    Missing_Query_details : "Veuillez entrer quelque chose pour rechercher des résultats dans la base de données"
}
